name: Lint Examples

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1

    - name: Install Depedencies
      env:
        dependency_packages: libvala-dev valac meson
      run: apt-get update && apt-get -y install ${dependency_packages}

    - name: Build
      run: meson build && ninja -C build

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: vala-lint
        path: ./build/src/io.elementary.vala-lint

  greeter:
    name: Greeter
    runs-on: ubuntu-latest
    needs: build

    container:
      image: elementary/docker:unstable

    steps:
    - name: Install Depedencies
      env:
        dependency_packages: libvala-dev valac git
      run: apt-get update && apt-get -y install ${dependency_packages}

    - name: Clone
      run: git clone https://github.com/elementary/greeter.git

    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: vala-lint
        path: ./build/src/io.elementary.vala-lint

    - name: Lint
      run: './build/src/io.elementary.vala-lint -d greeter/ || :'
