name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: |
        docker login -u ${{ secrets.DockerUsername }} -p ${{ secrets.DockerPassword }}
        docker build -t valalang/lint:latest .
        docker push valalang/lint:latest