name: Vala CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Depedencies
      run: |
        apt install -y libvala-0.40-dev
    - name: Build
      run: |
        meson build
        ninja -C build
    - name: Run Tests
      run: ninja test -C build
